project: 
  type: website
  
website: 
  page-navigation: true
  title: "Living Earth" 
  site-url: "https://ggiuliani.github.io/quarto/" 
  repo-url: "https://github.com/ggiuliani/quarto" 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-BY Living Earth Lab, 2026"
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Quarto website tutorial"
      - icon: twitter
        href: https://twitter.com/openscapes
        text: "Openscapes Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: introduction.qmd
        text: Introduction
      - href: howto.qmd
        text: How to use this handbook
      - href: documentation.qmd
        text: Documentation
      - section: tutorials/index.qmd
        contents: 
          - tutorials/tuto1.qmd
      - href: workshops.qmd
        text: Workshops  

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - quarto

  
